### ISSUE TITLE
[Question]Converting AST back to GLSL

### ISSUE THREAD

**Issue by rraallvv** [haxiomic/haxe-glsl-parser#6]
My use case is basically to be able to do the round trip from GLSL to AST and back to GLSL. So I was wondering whether there is any tool to get GLSL back from the AST generated by haxe-glsl-parser?
Regards.

**Comment by haxiomic** [comment]
Hey @rraallvv,

You can use the SyntaxPrinter class for this, all AST nodes are printable, so to print the AST you just print the root node

You can use it like:
```haxe
SyntaxPrinter.print(node, '\t')
```
To pretty-print indented with tabs, or
```haxe
SyntaxPrinter.print(node, null)
```
To print without any extraneious whitespace

I tend you use it as a `using` import, so you can do `node.print('\t')` instead

**Comment by haxiomic** [comment]
An example https://github.com/haxiomic/haxe-glsl-parser/blob/master/tests/demo/src/Main.hx#L61

**Comment by rraallvv** [comment]
Thank you @haxiomic, very much appreciated.
